local dap = require("dap")

-- pcall(function()
--   require("dap-view").setup({})
-- end)
--
-- pcall(function()
-- 	require("nvim-dap-virtual-text").setup({})
-- end)
--
--
-- vim.keymap.set("n", "<F5>", function()
-- 	local session = dap.session()
-- 	if not session then
-- 		dap.continue({ new = true })
-- 		return
-- 	end
-- 	if session.stopped_thread_id then
-- 		dap.continue()
-- 		return
-- 	end
-- 	vim.notify("Debuggee is running. Use <F6> to pause or <S-F5> to stop.", vim.log.levels.INFO)
-- end, { desc = "Debug start/continue" })
--
-- vim.keymap.set("n", "<F6>", function()
-- 	dap.pause()
-- end, { desc = "Debug pause" })
--
-- vim.keymap.set("n", "<S-F5>", function()
-- 	dap.terminate()
-- end, { desc = "Debug stop" })
--
-- vim.keymap.set("n", "<F10>", function()
-- 	dap.step_over()
-- end, { desc = "Debug step over" })
--
-- vim.keymap.set("n", "<F11>", function()
-- 	dap.step_into()
-- end, { desc = "Debug step into" })
--
-- vim.keymap.set("n", "<F12>", function()
-- 	dap.step_out()
-- end, { desc = "Debug step out" })
--
-- vim.keymap.set("n", "<Leader>b", function()
-- 	dap.toggle_breakpoint()
-- end, { desc = "Debug toggle breakpoint" })
--
-- vim.keymap.set({ "n", "v" }, "<leader>de", function()
-- 	require("dap.ui.widgets").hover()
-- end, { desc = "Debug eval under cursor/selection" })
--
-- vim.keymap.set("n", "<leader>dE", function()
-- 	vim.ui.input({ prompt = "DAP Eval> " }, function(expr)
-- 		if not expr or #expr == 0 then
-- 			return
-- 		end
-- 		dap.repl.open()
-- 		dap.repl.execute(expr, { context = "repl" })
-- 	end)
-- end, { desc = "Debug eval expression in REPL" })
--
-- vim.keymap.set("n", "<leader>dr", function()
-- 	dap.repl.open()
-- end, { desc = "Debug REPL open" })
--
-- vim.keymap.set("n", "<leader>du", "<cmd>DapViewToggle<cr>", { desc = "Debug view toggle" })
-- vim.keymap.set({ "n", "v" }, "<leader>dw", "<cmd>DapViewWatch<cr>", { desc = "Debug add watch" })
